server:
  port: 8081
spring:
  application:
    name: VKBackendTest
  datasource:
    url: jdbc:postgresql://postgres:5432/vk_test
    driverClassName: org.postgresql.Driver
    username: "admin"
    password: "admin"
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
token:
  signing:
    key: HldPJxTjwhAVfklMnZeLjqWzyXrpviDuNUCRtaYIBQoGSOgsKcFmbE